config/routes.rb
CSE337Application::Application.routes.draw do
  resources :inventories

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  attr_accessible :active, :description, :item_name, :price, :quantity, :upc_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inventories }
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/new
  # GET /inventories/new.json
  def new
    @inventory = Inventory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @inventory }
    end
  end

  # GET /inventories/1/edit
  def edit
    @inventory = Inventory.find(params[:id])
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(params[:inventory])

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url, notice: "#{@inventory.item_name} was successfully created." }
        format.json { render json: @inventory, status: :created, location: @inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /inventories/1
  # PUT /inventories/1.json
  def update
    @inventory = Inventory.find(params[:id])

    respond_to do |format|
      if @inventory.update_attributes(params[:inventory])
        format.html {redirect_to inventories_url, notice: "#{@inventory.item_name} was successfully updated."}
        format.json {head :no_content}
      else
        format.html { render action: "edit" }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notire: "Item successfully deleted"}
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
  <% if @inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
      <% @inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :upc_number %><br />
    <%= f.number_field :upc_number %>
  </div>
  <div class="field">
    <%= f.label :item_name %><br />
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<h1>Listing Inventories</h1>
<hr>
<%= link_to 'Create New Inventory', new_inventory_path %>
<hr>

<% @inventories.each do |inventory| %>
    <div class="span10 hero-unit">
      <div class="span6" style="float:left">
        <span class="upc_number"> <b> UPC Number: </b> <%= inventory.upc_number %> </span>
      </div>
      <div class="span3" style="float:right">
        <span class="quantity"> <b> Quantity: </b> <%= inventory.quantity %> </span>
      </div>
      <div class="span6" style="float:left">
        <span class="item_name"> <b> Item Name: </b> <%= inventory.item_name %></span>
      </div>
      <div class="span3" style="float:right">
        <span class="price"> <b> Price: </b> $<%= inventory.price %> </span>
      </div>
      <div class="desc span9"> <b>Description:</b> <%= inventory.description %>
      </div>
      <div class="span9" style="text-align: right;">
        <%= link_to "Edit".html_safe, edit_inventory_path(inventory) %>
      </div>
      <div class="span9" style="text-align: right;">
        <%= link_to "Delete", inventory_path(inventory), :method => "delete" %>
      </div>
    </div>
<% end %>

<br />

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<div class="span10 hero-unit">
<p id="notice"><%= notice %></p>

<p>
  <b>Upc number:</b>
  <%= @inventory.upc_number %>
</p>

<p>
  <b>Item name:</b>
  <%= @inventory.item_name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @inventory.quantity %>
</p>

<p>
  <b>Active:</b>
  <%= @inventory.active %>
</p>

<p>
  <b>Description:</b>
  <%= @inventory.description %>
</p>

<p>
  <b>Price:</b>
  <%= @inventory.price %>
</p>


<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">


  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link rel="stylesheet" href="css/bootstrap.min.css">
  <style>
      body {
          padding-top: 60px;
          padding-bottom: 40px;
      }
  </style>
  <link rel="stylesheet" href="css/bootstrap-responsive.min.css">
  <link rel="stylesheet" href="css/main.css">

  <script src="js/vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
</head>
<body>
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Goods Inc</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="nav-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form pull-right">
          <input class="span2" type="text" placeholder="Email">
          <input class="span2" type="password" placeholder="Password">
          <button type="submit" class="btn">Sign in</button>
        </form>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">

  <!-- Main hero unit for a primary marketing message or call to action -->
  ￼<div>
  <% flash.each do |type, msg| %>
      <% if msg.is_a?(String) %>
          <div class="alert alert-<%= type == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{@inventory}" %>
          </div>
      <% end %>
  <% end %>
  <%= yield %>


</div>

  <footer>
    <p>CSE 337</p>
  </footer>

</div> <!-- /container -->


</body>
</html>